### ISSUE TITLE
Not able to play videos with feature flag in URL

### ISSUE THREAD

**Issue by BorisL91** [gigantz/react-bigpicture#10]
https://www.youtube.com/watch?v=Z-VfaG9ZN_U&feature=youtu.be&t=60

**Comment by gigantz** [comment]
BigPicture library doesn't support feature flag for youtube, but in updated version of react-picture@1.0.24.
You can use **iframe** for that and pass the src like `https://www.youtube.com/embed/Z-VfaG9ZN_U?start=109` to embed.

this should work
```javascript
      <BigPicture
        type="iframe"
        src="https://www.youtube.com/embed/Z-VfaG9ZN_U?start=109"
      >
        <img src="http://lorempixel.com/400/200/sports/1" />
      </BigPicture>
```
