### ISSUE TITLE
Error: Prop type `noLoader` is invalid

### ISSUE THREAD

**Issue by EricYangTL** [gigantz/react-bigpicture#11]
I get this error in js console with a pretty basic implementation using version 2.1.3. Any thoughts on how to resolve?

![image](https://user-images.githubusercontent.com/44711742/63355963-9e1a1e80-c32c-11e9-884a-58cbeabaf17b.png)

```
<BigPicture className="watch-video" type="vimeo" src="https://vimeo.com/xyz">
  <img src={VideoSampleIcon} alt="Video"/>
  <span>Watch sample video (0:56)</span>
</BigPicture>
```

All still works as expected to the end user, I just don't want the console error to show up.

**Comment by gigantz** [comment]
thanks for catching, It was misspelled prop-type.

Fixed. Please upgrade to latest
```
npm i react-bigpicture@1.0.26
```
