### ISSUE TITLE
Don't define style={{ display: 'inline-block' }}

### ISSUE THREAD

**Issue by PatrickLerner** [gigantz/react-bigpicture#6]
This is an impediment to using this package in a lot of circumstances as it can not be easily overwritten and provides no real benefit to dictating it in the package.

**Comment by gigantz** [comment]
yes, true. I'll refactor all these parts today and update the package

**Comment by PatrickLerner** [comment]
Hey @gigantz Thanks! I actually submitted a pull request for this already :)
